AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormBot Lambda API with API Gateway

Resources:
  # Lambda Function
  FormBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/formbot-lambda:latest'
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          DYNAMODB_TABLE: form-bot-data
          DOCUMENTS_TABLE: formbot-documents
          S3_BUCKET: !Ref DocumentsBucket
          REDIS_HOST: formbot-redis-gz9sjn.serverless.use1.cache.amazonaws.com
          REDIS_PORT: '6379'
          REDIS_SSL: 'true'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: form-bot-data
        - DynamoDBCrudPolicy:
            TableName: formbot-documents
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
      Events:
        # User Registration
        UserRegister:
          Type: Api
          Properties:
            Path: /api/user/register
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Store Employee Data
        StoreData:
          Type: Api
          Properties:
            Path: /api/user/data
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Get User Data
        GetUserData:
          Type: Api
          Properties:
            Path: /api/user/data
            Method: GET
            RestApiId: !Ref FormBotAPI
        
        # Get Profiles
        GetProfiles:
          Type: Api
          Properties:
            Path: /api/profiles
            Method: GET
            RestApiId: !Ref FormBotAPI
        
        # Create Profile
        CreateProfile:
          Type: Api
          Properties:
            Path: /api/profiles
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Sync Endpoint
        Sync:
          Type: Api
          Properties:
            Path: /api/sync
            Method: GET
            RestApiId: !Ref FormBotAPI
        
        # Zapier Webhook Endpoint
        Webhook:
          Type: Api
          Properties:
            Path: /api/webhook
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Health Check
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            RestApiId: !Ref FormBotAPI
        
        # Get Field Mapping (Redis Cache)
        GetFieldMapping:
          Type: Api
          Properties:
            Path: /api/field-mapping
            Method: GET
            RestApiId: !Ref FormBotAPI
        
        # Post Field Mapping (Redis Cache)
        PostFieldMapping:
          Type: Api
          Properties:
            Path: /api/field-mapping
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Batch Field Mapping (Batch AI Matching)
        BatchFieldMapping:
          Type: Api
          Properties:
            Path: /api/batch-field-mapping
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Document Upload
        DocumentUpload:
          Type: Api
          Properties:
            Path: /api/documents/upload
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Save Document
        SaveDocument:
          Type: Api
          Properties:
            Path: /api/documents
            Method: POST
            RestApiId: !Ref FormBotAPI
        
        # Get Documents
        GetDocuments:
          Type: Api
          Properties:
            Path: /api/documents
            Method: GET
            RestApiId: !Ref FormBotAPI
        
        # Get Presigned URL
        GetPresignedUrl:
          Type: Api
          Properties:
            Path: /api/documents/presigned-url
            Method: GET
            RestApiId: !Ref FormBotAPI
        
        # Delete Document
        DeleteDocument:
          Type: Api
          Properties:
            Path: /api/documents/{documentId}
            Method: DELETE
            RestApiId: !Ref FormBotAPI

  # API Gateway
  FormBotAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET, POST, OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # DynamoDB Table
  FormBotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: form-bot-data
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: dataType
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: dataType
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: timestamp-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Documents DynamoDB Table
  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: formbot-documents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: documentId
          AttributeType: S
        - AttributeName: submittedAt
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: documentId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: submittedAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: submittedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # S3 Bucket for Documents
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'formbot-documents-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${FormBotAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: FormBotApiUrl
  
  TableName:
    Description: DynamoDB table name
    Value: !Ref FormBotTable

